<?php
return ['x-generator'=>'GlotPress/4.0.1','translation-revision-date'=>'2025-08-30 07:44:35+0000','plural-forms'=>'nplurals=1; plural=0;','project-id-version'=>'Plugins - List category posts - Stable (latest release)','language'=>'ja_JP','messages'=>['Include posts (id\'s)'=>'投稿 (ID) を含む','ID'=>'ID','Yes'=>'はい','No'=>'いいえ','Tags as class'=>'クラスとしてのタグ','Pagination'=>'ページ送り','These are general default options for List Category Posts. The idea in general will be that you can override them using the corresponding parameters in your shortcodes.'=>'これらは、リストカテゴリー投稿の一般的なデフォルト設定です。 一般的には、ショートコードの対応するパラメーターを使用して上書きすることができます。','http://fernandobriano.com'=>'http://fernandobriano.com','Fernando Briano'=>'Fernando Briano','List Category Posts allows you to list posts by category in a post/page using the [catlist] shortcode. This shortcode accepts a category name or id, the order in which you want the posts to display, the number of posts to display and many more parameters. You can use [catlist] as many times as needed with different arguments. Usage: [catlist argument1=value1 argument2=value2].'=>'List Category Postsでは、[catlist]ショートコードを使用して、ポスト/ページ内のカテゴリ別に投稿をリストすることができます。 このショートコードは、カテゴリ名またはID、投稿を表示する順序、表示する投稿数、さらに多くのパラメータを受け入れます。 [catlist]は、必要な回数だけさまざまな引数で使用できます。 使用法：[catlist argument1 = value1 argument2 = value2]','https://github.com/picandocodigo/List-Category-Posts'=>'https://github.com/picandocodigo/List-Category-Posts','List category posts'=>'List category posts','Fork on Github'=>'Fork on Github','Donate'=>'寄付','How to use'=>'使い方','List Category Posts'=>'List Category Posts','List posts from a specified category'=>'指定したカテゴリーの投稿を一覧表示する','Template'=>'テンプレート','More link'=>'追加リンク','Excerpt size'=>'抜粋サイズ','Excerpt'=>'抜粋','Link to category (use \'catlink\' on the title field if you want the title of this widget to be a link to the category)'=>'カテゴリーへのリンク (このウィジットのタイトルをカテゴリーにリンクしたい場合は、タイトル欄に \'catlink\' を使用してください)','Thumbnail - size'=>'サムネイル - サイズ','Show'=>'表示','Exclude posts (id\'s)'=>'投稿を除外 (ID)','Exclude categories (id\'s)'=>'カテゴリーを除外 (ID)','Ascending'=>'昇順','Descending'=>'降順','Order'=>'順序','Random'=>'ランダム','Author'=>'登録者','Post title'=>'投稿タイトル','Modified Date'=>'更新日','Date'=>'日付','Order by'=>'順序','Offset'=>'オフセット','Number of posts'=>'投稿数','Category'=>'カテゴリー','Title'=>'タイトル','If you\'ve found the plugin useful, consider making
      a <a href=\'http://picandocodigo.net/programacion/wordpress/list-category-posts-wordpress-plugin-english/\'
      title=\'Donate via PayPal\' rel=\'nofollow\'>donation via PayPal</a>
      or visit my Amazon Wishlist
      for <a href=\'http://www.amazon.com/gp/registry/wishlist/2HU1JYOF7DX5Q/ref=wl_web\'
      title=\'Amazon Wishlist\' rel=\'nofollow\'>books</a>
      or <a href=\'http://www.amazon.com/registry/wishlist/1LVYAOJAZQOI0/ref=cm_wl_rlist_go_o\'
      rel=\'nofollow\'>comic books</a> :).'=>'プラグインが役に立った場合は、
      <a href=\'http://picandocodigo.net/programacion/wordpress/list-category-posts-wordpress-plugin-english/\'
      title=\'Donate via PayPal\' rel=\'nofollow\'>PayPal で寄付</a>するか、私の Amazon ウィッシュリストにアクセスして、<a href=\'http://www.amazon.com/gp/registry/wishlist/2HU1JYOF7DX5Q/ref=wl_web\'
      title=\'Amazon Wishlist\' rel=\'nofollow\'>書籍</a>
      または <a href=\'http://www.amazon.com/registry/wishlist/1LVYAOJAZQOI0/ref=cm_wl_rlist_go_o\'
      rel=\'nofollow\'>コミック本</a>を探してください。','Please post <strong>new feature requests, Bug fixes,
      enhancements</strong>
      to <a href=\'https://github.com/picandocodigo/List-Category-Posts/issues\'>GitHub
      Issues</a> and check out the
      the <a href=\'https://github.com/picandocodigo/List-Category-Posts\'>GitHub
      repo</a> if you want to contribute code.'=>'<strong>新しい機能リクエスト、バグ修正、機能拡張</strong>を <a href=\'https://github.com/picandocodigo/List-Category-Posts/issues\'>GitHubに投稿</a>し、コードを投稿したい場合は<a href=\'https://github.com/picandocodigo/List-Category-Posts\'>GitHubリポジトリをチェック</a>してください。','If you need help with the plugin, please visit
      the <a href=\'http://wordpress.org/support/plugin/list-category-posts\'>WordPress
      support forum</a>. Make sure
      you <a href=\'http://wordpress.org/extend/plugins/list-category-posts/other_notes/\'>read
      the instructions</a> to be aware of all the things you can do
      with List Category Posts and <a href=\'https://github.com/picandocodigo/List-Category-Posts/blob/master/doc/FAQ.md#frequently-asked-questions\'>check out the FAQ</a>.'=>'プラグインのヘルプが必要な場合は、<a href=\'http://wordpress.org/support/plugin/list-category-posts\'>WordPress サポートフォーラムにアクセスしてください</a>。
<a href=\'http://wordpress.org/extend/plugins/list-category-posts/other_notes/\'>手順を読んで</a> List Category Posts でできることをすべて認識し、<a href=\'https://github.com/picandocodigo/List-Category-Posts/blob/master/doc/FAQ.md#frequently-asked-questions\'>FAQ をチェック</a>してください。','Thanks for using List Category Posts.'=>'List Category Posts を使用していただきありがとうございます。','-1 - displays ALL THE POSTS (no limit)'=>'-1 - すべての投稿を表示 (無制限)','0 - displays the max number of posts per page'=>'0 - ページあたりの投稿の最大数を表示する','Default number of posts (overriden using <code>numberposts</code> parameter on each shortcode).'=>'デフォルトの投稿数 (各ショートコードの <code>numberposts</code> パラメータを使用して上書きします)。','Number of Posts'=>'投稿数','You do not have sufficient permissions to access this page.'=>'このページを表示する権限がありません。','Continue reading &rarr;'=>'続きを読む &rarr;','Empty Term.'=>'タームが空です。']];