<?php
if (!defined('ABSPATH')) {
	exit;
}

/**
 * Centralized editor defaults used when switching template/layout mode.
 *
 * @since 2.4.0
 *
 * @return array
 */
function easy_sticky_sidebar_get_editor_default_templates() {
	$overlay_image = EASY_STICKY_SIDEBAR_PLUGIN_URL . '/assets/img/overlay_dummy.webp';
	$overlay_image_right = EASY_STICKY_SIDEBAR_PLUGIN_URL . '/assets/img/overlay_dummy_right.webp';
	$overlay_image_top = EASY_STICKY_SIDEBAR_PLUGIN_URL . '/assets/img/ss_dummy_overlay_top.jpg';
	$classic_image = EASY_STICKY_SIDEBAR_PLUGIN_URL . '/assets/img/overlay_dummy.webp';
	$shared_letter_spacing_defaults = array(
		'letter_spacing'              => '0',
		'content_letter_spacing'      => '0',
		'call_to_action_letter_spacing' => '0',
		'button2_letter_spacing'      => '0',
		'enable_cta_width'            => 'no',
		'enable_cta_height'           => 'no',
	);
	$zero_content_padding_defaults = array(
		'content_padding[top]'    => '0',
		'content_padding[right]'  => '0',
		'content_padding[bottom]' => '0',
		'content_padding[left]'   => '0',
		'content_padding[unit]'   => 'px',
	);

	return array(
		'templates' => array(
			'tab-cta' => array_merge($shared_letter_spacing_defaults, $zero_content_padding_defaults, array(
				'sidebar_template'                => 'tab-cta',
				'button_round'                    => '5',
				'show_close_button'              => 'no',
				'SSuprydp_button_option_text'     => 'Call Now',
				'SSuprydp_button_option_backg_color' => '#218400',
				'SSuprydp_button_option_color'    => '#ffffff',
				'SSuprydp_button_option_font'     => 'Arial',
				'button_icon_size'                => '16',
				'button_icon_position'            => 'before',
				'button_text_orientation'         => 'top-to-bottom',
				'SSuprydp_button_option_size'     => '24',
			)),
			'floating-buttons' => array_merge($shared_letter_spacing_defaults, $zero_content_padding_defaults, array(
				'sidebar_template'                     => 'floating-buttons',
				'show_close_button'                    => 'no',
				'SSuprydp_cta_position'                => 'right',
				'horizontal_vertical_position'         => 'center',
				'floating_button_color'                => '#ffffff',
				'floating_button_hover_color'          => '#ffffff',
				'floating_button_background_color'     => '#11265d',
				'floating_button_background_hover_color' => '#2466d5',
				'hide_floating_button_text'            => 'no',
			)),
			'banner' => array_merge($shared_letter_spacing_defaults, $zero_content_padding_defaults, array(
				'sidebar_template'                  => 'banner',
				'SSuprydp_cta_position'             => 'top',
				'SSuprydp_content_option_text'      => 'This is the Content Area.',
				'SSuprydp_action_option_text'       => 'Click Here to View',
				'SSuprydp_action_option_url'        => 'https://wpctapro.com/',
				'SSuprydp_content_option_color'     => '#ffffff',
				'SSuprydp_action_option_color'      => '#ffffff',
				'content_background_color'          => '#1f2937',
				'link_text_background'              => '#099607',
				'call_to_action_button'             => 'no',
				'close_button_color'                => '#ffffff',
				'close_button_position'             => 'right',
				'show_close_button'                 => 'no',
				'content_padding[top]'              => '10',
				'content_padding[right]'            => '10',
				'content_padding[bottom]'           => '10',
				'content_padding[left]'             => '10',
				'content_padding[unit]'             => 'px',
				'banner_content_padding[top]'       => '10',
				'banner_content_padding[right]'     => '10',
				'banner_content_padding[bottom]'    => '10',
				'banner_content_padding[left]'      => '10',
				'banner_content_padding[unit]'      => 'px',
				'banner_button_padding[top]'        => '10',
				'banner_button_padding[right]'      => '10',
				'banner_button_padding[bottom]'     => '10',
				'banner_button_padding[left]'       => '10',
				'banner_button_padding[unit]'      => 'px'
			)),
			'html' => array_merge($shared_letter_spacing_defaults, array(
				'sidebar_template'                  => 'html',
				'button_round'                      => '5',
				'show_close_button'                 => 'no',
				'enable_cta_width'                  => 'yes',
				'cta_width'                         => '450',
				'cta_width_unit'                    => 'px',
				'enable_cta_height'                 => 'yes',
				'cta_height'                        => '250',
				'cta_height_unit'                   => 'px',
				'SSuprydp_button_option_text'       => 'Click Here',
				'SSuprydp_content_option_text'      => '<h3>This is the Content Area. Put a description here of what you want to promote.</h3><p>This is demo pragraph</p>',
				'SSuprydp_button_option_backg_color' => '#099607',
				'SSuprydp_button_option_color'      => '#ffffff',
				'SSuprydp_content_option_color'     => '#000000',
				'content_background_color'          => '#ffffff',
				'content_padding[top]'             => '10',
				'content_padding[right]'           => '10',
				'content_padding[bottom]'          => '10',
				'content_padding[left]'            => '10',
				'content_padding[unit]'            => 'px',
				'SSuprydp_content_option_font'      => 'Arial',
				'SSuprydp_button_option_font'       => 'Archivo:700',
			)),
			'gdpr' => array_merge($shared_letter_spacing_defaults, $zero_content_padding_defaults, array(
				'sidebar_template'                  => 'gdpr',
				'SSuprydp_content_option_text'      => 'This site uses cookies to improve your experience.',
				'SSuprydp_content_option_color'     => '#ffffff',
				'content_background_color'          => '#1f2937',
				'content_padding[top]'              => '15',
				'content_padding[right]'            => '15',
				'content_padding[bottom]'           => '15',
				'content_padding[left]'             => '15',
				'content_padding[unit]'             => 'px',
				'SSuprydp_button_option_size'       => '18',
				'SSuprydp_button_option_font'       => 'Archivo:600',
				'SSuprydp_content_option_font'      => 'Arial',
				'SSuprydp_content_option_size'      => '18',
				'gdpr_box_radius'                   => '8',
				'SSuprydp_button_option_text'       => 'Accept',
				'SSuprydp_button_option_backg_color' => '#099607',
				'SSuprydp_button_option_color'      => '#ffffff',
				'button2_show'                      => 'no',
				'button2_text'                      => 'Decline',
				'button2_background_color'          => '#374151',
				'button2_text_color'                => '#ffffff',
				'close_button_position'             => 'top-right',
				'show_close_button'                 => 'no',
			)),
		),
		'sticky_layouts' => array(
			'classic' => array_merge($shared_letter_spacing_defaults, $zero_content_padding_defaults, array(
				'sidebar_template'                  => 'sticky-cta',
				'button_round'                      => '5',
				'show_close_button'                 => 'no',
				'enable_cta_width'                 => 'no',
				'cta_width'                        => '500',
				'cta_width_unit'                   => 'px',
				'enable_cta_height'                => 'no',
				'cta_height'                       => '300',
				'cta_height_unit'                  => 'px',
				'image_placement'                   => 'classic',
				'overlay_position'                  => 'right',
				'sticky_s_media'                    => $classic_image,
				'image_attachment_id'               => '0',
				'hide_cta_image'                    => 'no',
				'cta_image_height'                  => '200',
				'SSuprydp_button_option_text'       => 'Click Here',
				'SSuprydp_content_option_text'      => 'This is the Content Area. Put a description here of what you want to promote.',
				'SSuprydp_action_option_text'       => 'Click Here to View',
				'button_icon_size'                 => '16',
				'button_icon_position'             => 'before',
				'button_text_orientation'          => 'top-to-bottom',
				'SSuprydp_button_option_backg_color' => '#099607',
				'SSuprydp_button_option_color'      => '#ffffff',
				'link_text_background'              => '#3778dc',
				'SSuprydp_action_option_color'      => '#ffffff',
				'content_background_color'          => '#ffffff',
				'SSuprydp_content_option_color'     => '#000000',
				'SSuprydp_content_option_size'      => '20',
				'SSuprydp_action_option_size'       => '20',
				'overlay_backdrop_color'            => '#ffffff',
				'overlay_backdrop_opacity'          => '70',
				'content_padding[top]'              => '14',
				'content_padding[right]'            => '24',
				'content_padding[bottom]'           => '14',
				'content_padding[left]'             => '24',
				'content_padding[unit]'             => 'px',
				'call_to_action_padding[top]'       => '14',
				'call_to_action_padding[right]'     => '24',
				'call_to_action_padding[bottom]'    => '14',
				'call_to_action_padding[left]'      => '24',
				'call_to_action_padding[unit]'      => 'px',
			)),
			'overlay-left' => array_merge($shared_letter_spacing_defaults, $zero_content_padding_defaults, array(
				'sidebar_template'                  => 'sticky-cta',
				'button_round'                      => '5',
				'show_close_button'                 => 'no',
				'image_placement'                   => 'overlay',
				'overlay_position'                  => 'left',
				'sticky_s_media'                    => $overlay_image,
				'image_attachment_id'               => '0',
				'hide_cta_image'                    => 'no',
				'cta_image_height'                  => '300',
				'SSuprydp_button_option_text'       => 'Have Questions?',
				'SSuprydp_content_option_text'      => 'Get quick answers and expert guidance tailored to your needs.',
				'SSuprydp_action_option_text'       => 'Get Started',
				'button_icon_size'                 => '16',
				'button_icon_position'             => 'before',
				'button_text_orientation'          => 'top-to-bottom',
				'SSuprydp_button_option_backg_color' => '#099607',
				'SSuprydp_button_option_color'      => '#ffffff',
				'link_text_background'              => '#08a800',
				'SSuprydp_action_option_color'      => '#ffffff',
				'content_background_color'          => '',
				'SSuprydp_content_option_color'     => '#383838',
				'SSuprydp_content_option_font'      => 'Arial',
				'SSuprydp_content_option_size'      => '24',
				'SSuprydp_action_option_font'       => 'Archivo:700',
				'SSuprydp_action_option_size'       => '24',
				'overlay_backdrop_color'            => '#ffffff',
				'overlay_backdrop_opacity'          => '70',
				'overlay_width'                     => '60',
				'overlay_content_padding'           => '12',
				'overlay_content_margin[top]'       => '50',
				'overlay_content_margin[right]'     => '0',
				'overlay_content_margin[bottom]'    => '50',
				'overlay_content_margin[left]'      => '0',
				'overlay_content_margin[unit]'      => 'px',
				'overlay_content_alignment'         => 'left',
				'overlay_button_alignment'          => 'left',
				'overlay_button_padding[top]'       => '5',
				'overlay_button_padding[right]'     => '20',
				'overlay_button_padding[bottom]'    => '5',
				'overlay_button_padding[left]'      => '20',
				'overlay_button_padding[unit]'      => 'px',
				'overlay_button_radius'             => '50',
				'overlay_full_tab_height'           => 'yes',
				'overlay_tab_text_orientation'      => 'top-to-bottom',
				'overlay_tab_corner_radius'         => '5',
			)),
			'overlay-right' => array(
				'sticky_s_media'            => $overlay_image_right,
				'overlay_position'          => 'right',
				'overlay_content_alignment' => 'right',
				'overlay_button_alignment'  => 'right',
			),
			'overlay-top' => array(
				'sticky_s_media'            => $overlay_image_top,
				'overlay_position'          => 'top',
				'overlay_content_margin[top]'    => '20',
				'overlay_content_margin[right]'  => '0',
				'overlay_content_margin[bottom]' => '20',
				'overlay_content_margin[left]'   => '0',
				'overlay_content_alignment' => 'center',
				'overlay_button_alignment'  => 'center',
			),
			'overlay-bottom' => array(
				'overlay_position'          => 'bottom',
				'overlay_content_margin[top]'    => '20',
				'overlay_content_margin[right]'  => '0',
				'overlay_content_margin[bottom]' => '20',
				'overlay_content_margin[left]'   => '0',
				'overlay_content_alignment' => 'center',
				'overlay_button_alignment'  => 'center',
			),
		),
	);
}
